<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Flurl" Version="4.0.0"/>
        <PackageReference Include="Flurl.Http" Version="4.0.2"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.10"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="10.0.10"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.10"/>
        <PackageReference Include="Quartz" Version="3.18.2"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\IDM.Application\IDM.Application.csproj"/>
        <ProjectReference Include="..\IDM.Domain\IDM.Domain.csproj"/>
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Synchronization\Departments\Tree\" />
    </ItemGroup>

</Project>
