<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <Folder Include="Mappings\"/>
        <Folder Include="Synchronization\Departments\Tree\" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\IDM.Domain\IDM.Domain.csproj"/>
    </ItemGroup>

</Project>
